# Generated by Django 5.2.5 on 2025-09-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='statut',
            field=models.CharField(choices=[('published', 'Publié'), ('archived', 'Archivé'), ('draft', 'Brouillon')], default='draft', max_length=20),
        ),
    ]
