# Generated by Django 5.2.5 on 2025-08-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='statut',
            field=models.CharField(choices=[('published', 'Publié'), ('draft', 'Brouillon'), ('archived', 'Archivé')], default='draft', max_length=20),
        ),
    ]
