# Generated by Django 5.2.5 on 2025-09-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_event_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='statut',
            field=models.CharField(choices=[('archived', 'Archivé'), ('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
